y-crdt/y-crdt

- Cargo.lock
- Cargo.toml
- yrs/src/block.rs
- yrs/src/block_store.rs
- yrs/src/compatibility_tests.rs
- yrs/src/doc.rs
- yrs/src/event.rs
- yrs/src/id_set.rs
- yrs/src/lib.rs
- yrs/src/store.rs
- yrs/src/transaction.rs
- yrs/src/types/text.rs
- yrs/src/update.rs
Merge after #22
This PR introduces tests used to check if we can correctly serialize/deserialize content produced by Yjs (v13).
> [WIP] binary compatibility tests

- Cargo.lock
- Cargo.toml
- yrs/src/block.rs
- yrs/src/block_store.rs
- yrs/src/doc.rs
- yrs/src/event.rs
- yrs/src/id_set.rs
- yrs/src/store.rs
- yrs/src/transaction.rs
- yrs/src/types/text.rs
- yrs/src/update.rs
Merge after #21
This PR used event handlers defined in the past and incorporates them into publish/subscribe for `update` application event. For sample scenario, see test.
> Ability to subscribe to incoming updates

- Cargo.lock
- lib0/src/decoding.rs
- y-py/Cargo.toml
- y-py/src/lib.rs
- yrs-api-wrapper/Cargo.toml
- yrs/src/alt.rs
- yrs/src/block.rs
- yrs/src/lib.rs
- yrs/src/update.rs
- yrs/src/updates/decoder.rs
Ported: https://docs.yjs.dev/api/document-updates#alternative-update-api
The code is compiling but atm it's not jet verified to work properly.
> [WIP] Alternative update API

- yrs/src/block_store.rs
- yrs/src/doc.rs
- yrs/src/id_set.rs
- yrs/src/lib.rs
- yrs/src/test_utils.rs
- yrs/src/update.rs
WORK IN PROGRESS: This is the beginning of a fuzzy testing framework ported from Yjs.
> [WIP] Simulation testing framework

- yrs/src/update.rs
#29 broke git history. This is good and ready to merge.
> Update::encode_diff fixed client sorting

- yrs/src/block.rs
- yrs/src/block_store.rs
- yrs/src/compatibility_tests.rs
- yrs/src/store.rs
- yrs/src/test_utils.rs
- yrs/src/transaction.rs
- yrs/src/types/array.rs
- yrs/src/types/map.rs
- yrs/src/types/mod.rs
- yrs/src/update.rs
Depends on #30 . This is implementation of YArray.
> YArray implementation

- Cargo.lock
- y-py/Cargo.toml
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations
> included versioning in cargo files for purposes of cargo release

- yrs/src/types/array.rs
- yrs/src/types/mod.rs
Fixes https://github.com/y-crdt/y-crdt/issues/81
If I made any guideline mistakes, remarks and reviews are welcome!
> [yrs] Fix infinite loop caused by crossing deleted items in YArray

- yrs/src/types/text.rs
> Fixed missing assignment of ItemPosition::left during block split in Text::format

- yrs/src/doc.rs
- yrs/src/event.rs
- yrs/src/store.rs
- yrs/src/transaction.rs
Created an initial draft of the transaction cleanup hook. @Horusiath @dmonad I would love some feedback:
- Should I include the `after_set` or a diff between the after set and before set?
- Should any other data other than the data vectors be included?
> Transaction Cleanup Hook

- yrs/src/block.rs
- yrs/src/transaction.rs
- yrs/src/updates/decoder.rs
- applying remote delete set with client id not known on local block store
- integrate outdated YMap's block with conflict resolution combined with squashing past deleted blocks
- integrate block with removed parent
> Fixes for bugs found using small data set (part 1)

- Cargo.lock
- lib0/Cargo.toml
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Fixing encode with offset issues.
> release v0.9.1

- yrs/src/block.rs
- yrs/src/types/map.rs
- yrs/src/types/text.rs
- yrs/src/types/xml.rs
Closes #135
Let me know if this is needed or not. I will be happy to rewrite this
change if I totally got it wrong :)
> Implement public PrelimText for nesting

- yrs/src/types/text.rs
> fixed string formatting attributes missing in Text::diff

- yrs/src/types/text.rs
> fixed utf8/utf16 offset mapping issue

- yrs/src/types/text.rs
Hi,
Recently, I was preparing to move to yrs from yjs on my iOS app due to unstable WebKit and relevant slow JavaScriptCore. So I ran some performance tests. One of those tests contains 12000+ inserts with all kinds of different attributes and takes approximately 70 seconds to finish on an iPhone 6s (40 seconds on i9-9880H iOS Simulator), while yjs on the same device using JavaScriptCore only take around a second.
Down below are some profiling info from the Instruments app of Xcode (Weight and Symbol).
```
1.17 min 93.8%   yrs::types::text::Text::insert_with_attributes
1.17 min 93.5%   yrs::types::text::Text::find_position
57.89 s  77.0%   yrs::types::text::Text::update_current_attributes
21.84 s  29.0%   _$LT$hashbrown..raw..RawTable$LT$T$C$A$GT$$u20$as$u20$core..clone..Clone$GT$::clone …
```
> Optimize find_position performance

- lib0/src/decoding.rs
- lib0/src/error.rs
- yffi/src/lib.rs
- yrs/src/alt.rs
- yrs/src/doc.rs
- yrs/src/types/xml.rs
- yrs/src/updates/decoder.rs
- ywasm/src/lib.rs
> DecoderV2::read_buf - check expected length before reading

- yrs/src/types/xml.rs
> added XmlText methods: diff and diff_range

- yrs/src/types/xml.rs
> Fixed XmlElementRef::to_string attribute quotations

- yrs/src/types/text.rs
Fixes https://github.com/y-crdt/y-crdt/issues/231
> Document OffsetKind usage in Text::insert

- Cargo.lock
- lib0/Cargo.toml
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- introduced `StickyIndex` (previously `RelativePosition`)
- yffi: changed integer types to use stdint.h defintions for cross-platform compatilibity
- fixed `TransactionMut::after_state`
- improved rust docs
- attached Yrs logo
> release v0.16

- yrs/src/doc.rs
- yrs/src/types/mod.rs
> Fixed infinite loop recursion in doc.to_json when subdoc included

- yrs/src/types/xml.rs
This PR fixes bug reported in #260 .
> fixed infinite loop in deleted XML nodes

- Cargo.lock
- lib0/Cargo.toml
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Fixed #260 : infinite loops inside of XML tree walker iterator
> release v0.16.2

- Cargo.lock
- lib0/Cargo.toml
- yffi/Cargo.toml
- yrs/Cargo.toml
- yrs/README.md
- ywasm/Cargo.toml
> release v0.16.3

- yrs/src/id_set.rs
> fix IdRange::merge returns the wrong result when b is completely inside a.

- lib0/src/any.rs
> removed panic from Any::decode

- Cargo.lock
- lib0/Cargo.toml
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
> release v0.16.5

- yrs/src/doc.rs
- yrs/src/store.rs
Related to issue noticed by @LSViana at https://github.com/LSViana/ydotnet/issues/6
> Fixed snapshot encoding when full struct is included

- Cargo.lock
- lib0/Cargo.toml
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Fixed snapshots encoding when full client update trace is being encoded
> release v0.16.8

- yrs/src/types/map.rs
- yrs/src/types/xml.rs
> Yjs compatibility: changed inserted XML attribute value from content Text to content Any

- Cargo.lock
- lib0/Cargo.toml
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Fixed #303 - changed underlying data type for XML attribute insert from `ItemContent::String` to `ItemContent::Any`
> release v0.16.9

- Cargo.lock
- lib0/benches/lib0_benchmarks.rs
- tests-wasm/testHelper.js
- tests-wasm/y-array.tests.js
- tests-wasm/y-map.tests.js
- tests-wasm/y-text.tests.js
- tests-wasm/y-xml.tests.js
- yffi/src/lib.rs
- ywasm/src/lib.rs
> Add origin property getter to Ywasm events

- Cargo.lock
- lib0/Cargo.toml
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
> release-v0.16.10

- .github/workflows/release.yml
- Cargo.lock
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Fixes to conditional `feature=["weak"]` - when not turned on, it was causing project compilation to fail for some reason (even though it was passing builds locally).
> release-v0.17.1

- yrs/src/block.rs
- yrs/src/transaction.rs
- yrs/src/undo.rs
> fix issue 371: incorrect doc state after undo

- Cargo.lock
- yffi/Cargo.toml
- yrs/Cargo.toml
- yrs/src/block.rs
- ywasm/Cargo.toml
- removed stale `println!` statement: #371
> release v0.17.4

- Cargo.lock
- yffi/src/lib.rs
- yrs/Cargo.toml
- yrs/src/doc.rs
- yrs/src/lib.rs
- yrs/src/test_utils.rs
- yrs/src/types/array.rs
- yrs/src/types/map.rs
- yrs/src/types/text.rs
Related to https://github.com/y-crdt/yswift/issues/42
> replace rand crate with fastrand

- yrs/src/moving.rs
- yrs/src/store.rs
- yrs/src/tests/edit_traces.rs
- yrs/src/tests/edit_traces_tests.rs
- yrs/src/undo.rs
> fix undo manager issue #380

- tests-ffi/main.cpp
- yffi/src/lib.rs
> Remove unnecessary Branch pointer wrapping in yffi event target

- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Fixes #404 
- Expose pending DeleteSet and PendingUpdate for the users API: #409
> release v0.18.2

- yrs/src/doc.rs
- yrs/src/transaction.rs
- yrs/src/update.rs
> Fix issue with missing out of order updates

- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- fix issue with disappearing out-of-order updates: #414
- add auto implemented Clone to ysync message: #416
> release v0.18.3

- yrs/benches/benches.rs
- yrs/benches/serialization.rs
- yrs/src/encoding/mod.rs
- yrs/src/encoding/varint.rs
- yrs/src/error.rs
- yrs/src/observer.rs
- yrs/src/updates/decoder.rs
- yrs/src/updates/encoder.rs
Fixes the `has_subscribers` method. I've also added a test case for the same.
Fixes #418
> [yrs] fix `has_subscribers` on observer

- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Added `awareness::Event::awareness_update` method: #421
> release v0.18.4

- yrs/src/sync/awareness.rs
This PR add new method: `Awareness::apply_update_summary` which returns an optional `AwarenessUpdateSummary` object containing the information about any potential clients changed in result of applying the awareness update.
This enables us to bypass the closure limitations of subscriptions, eg.:
```rust
awareness.on_update(|event| {
// we don't know what was the origin at this point
broadcast(event.awareness_update(), except: origin); // we cannot use async methods 
});
let Message { origin, update } = message;
awareness.apply_update(update)?; // we cannot pass any additional data
```
Vs. using new API:
```rust
let Message { origin, update } = message;
if let Some(summary) = awareness.apply_update_summary(update)? {
let update = awareness.update_with_clients(summary.all_changes()); …
```
> add Awareness::apply_update_summary method

- Cargo.lock
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- fix `Text::insert_with_attributes` on empty string: #426
> release v0.18.6

- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Add more Awareness introspection features in Awareness::on_update event: #433
> release v0.18.8

- tests-ffi/main.cpp
- yffi/src/lib.rs
> yffi: stop forcing Any conversion on Y_MAP input

- tests-ffi/include/libyrs.h
- tests-ffi/main.cpp
- yffi/src/lib.rs
- yrs/src/lib.rs
- yrs/src/undo.rs
- ywasm/src/undo.rs
> UndoManager with no default scope

- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
Closes #451 
See related issue for details.
> release v0.19

- yrs/src/types/array.rs
- yrs/src/types/map.rs
Just like `Map::get_as` introduced in #465 , this PR introduces similar method for `Array`.
> Array::get_as

- yrs/src/undo.rs
> UndoManager: undo_stack and redo_stack access methods

- tests-ffi/include/libyrs.h
- tests-ffi/main.cpp
- yffi/src/lib.rs
This PR extends yffi API with functions and types enabling users to made sequences of changes onto YText/YXmlText types. These are useful ie. for performance-sensitive copy-pasting of rich formatted inputs.
- `ytext_insert_delta` function used for applying delta onto text:
-  `ydelta_input_retain` function for building retain (with optional formatting) delta fragments.
- `ydelta_input_delete` function for building delete delta fragments.
- `ydelta_input_insert` function for building insert (with optional formatting) delta fragments.
**BREAKING CHANGE**: `YDelta` type was renamed to `YDeltaOut` since now we also have delta used as input types &rarr; `YDeltaIn`.
> yffi: ytext_insert_delta function

- Cargo.lock
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Exposed `TransactionAcq` and `TransactionMutAcq` futures.
- #492 : make `StateVector` partially ordered.
> release v0.21.1

- Cargo.lock
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- #492 : add comparison implementation to `StateVector`
- #503 : TransactionMut::force_gc method
> release v0.21.2

- Cargo.lock
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- #509 : Update::state_vector_lower + Update::delete_set
> release v0.21.3

- yrs/src/block_store.rs
- yrs/src/id_set.rs
This change set introduces an optimization to Yrs garbage collection squashing.
To further enhance the scalability of the garbage collection (GC) process in DeleteSet, we've introduced a bulk squashing method that optimizes performance when handling large quantities of GC block cells. The previous per-block handling of squash calls worked well for many use cases. By implementing bulk squashing, we aim to reduce the overhead from constant reallocations while removing individual BlockCells (both GC and Block types).
In our internal benchmark focusing on contiguous removals, we observed that the delete operation GC collection time decreased from 118 seconds to 400 milliseconds in release builds, representing a substantial performance improvement. (Please note, the benchmark uses proprietary …
> DeleteSet: optimize GC squash for improved performance

- yrs/src/update.rs
Related to #525 
1. `Update::state_vector`: no longer counts blocks after `Skip` into returned state vector.
2. Removed `Update::lower_state_vector`: it's not very useful in presence of skip blocks.
3. Added `Update::extends` method: it allows to check if data inside of an update will add new information to a document given its state vector - this DOES NOT count data that would land in a pending update as new information because the state vector param itself doesn't take pending update into account.
> Update: fix state_vector, remove lower_state_vector and add Update::extends

- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- #541: support JsonPath over `Out::UndefinedRef`
- #539: fix panics when displaying events with removed elements
- #535: yffi - add `yweak_read` function to read quoted strings
> release v0.23.1

- yrs/src/update.rs
This is more revisioned version of #545 - thanks to the courtesy of @catssay we could pinpoint the issue.
> fixed Skip block encoding in lib0 v2

- .github/workflows/release.yml
- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- fixed skip block decoding in lib0 v2 deserialiser: #548 
- fixed read-after-free issue on weak links: #550
> release v0.23.2

- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- added `ReadTxn::has_missing_updates` method: #552 
- added `WriteTxn::prune_pending` method: #552
> release v0.23.3

- Cargo.lock
- yrs/Cargo.toml
- yrs/src/doc.rs
- yrs/src/lib.rs
Current UUID v4 generation doesn't produce a valid parseable UUIDs. This PR fixes that. I also makes UUID string generation faster.
> fix uuid generation

- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- yrs/src/transaction.rs
- ywasm/Cargo.toml
- fixed bug in `ReadTxn::has_missing_updates`: #554 
- fixed bug in uuid generation: #555
> release-v0.23.4

- yrs/src/update.rs
This PR:
1. Brings back `Update::state_vector_lower` which was [present in the past](https://github.com/y-crdt/y-crdt/pull/526/files), but later removed.
2. Introduces `Update::insertions` - a method that returns an `IdSet` (similar to delete set) which represents block id ranges for all blocks inserted as result of this update.
> Update::insertions and Update::state_vector_lower

- Cargo.lock
- tests-wasm/package-lock.json
- yffi/Cargo.toml
- yrs/Cargo.toml
- ywasm/Cargo.toml
- Added `Update::state_vector_lower` method: #564
- Added `Update::insertions` method: #564
- Extended quotations to work with unbounded ranges: #557
> release v0.23.5
