y-crdt/y-crdt

yrs/src/block.rs
yrs/src/block_store.rs
yrs/src/doc.rs
yrs/src/store.rs
yrs/src/types/text.rs

I had some uncommitted work on my computer (WIP). We don't have to merge this because some of it was already addressed by #3. This implements, for example, the `len()` method on generic blocks.  @Horusiath

adding uncommitted work

---

Cargo.toml
yrs-python/Cargo.toml
yrs-python/README.md
yrs-python/pyproject.toml
yrs-python/src/lib.rs
yrs-python/tests/sample_code.py

First version of the yrs-python wrapper
- it binds to python the methods of `yrs-api-wrapper`
- `yrs-python` relies on `maturin`. Check the `readme` for more details.
- Tested through a sample code that we'll enhance once `yrs-api-wrapper` is completed

First version of the yrs-python wrapper

---

.gitignore
lib0/src/any.rs

This PR add support of convert native Rust data types into Any struct:
- `bool`
- `f32`/`f64`
- `i32`/`i64`
- `u32` (conversion from `u64` not included as it's not safe)
- `String`/`&str`
- `Box<[u8]>`/`Vec<u8>`
- `Option<T>` of convertible type (to support null conversion)
- `Vec<T>` of convertible type (for array)
- `HashMap<String,T>` of convertible type as value
Additionally implemented `std::fmt::Display` trait which is used i.e. in `println!("{}", any_value)`. Printing convert's Any value into JSON-like string.

Any: implemented Into conversion for supported types + Display

---

yrs/src/block.rs
yrs/src/block_store.rs
yrs/src/doc.rs
yrs/src/lib.rs
yrs/src/store.rs
yrs/src/types/text.rs

In general I've seen that a lot of encoding/decoding logic here is inlined into calling methods. I think we could optimize it into a kind of `Encode`/`Decode` traits and just implement them for necessary cases eg.:
```rust
trait Encode {
fn encode(&self, encoder: &mut Encoder);
}
trait Decode {
fn decode(decoder: &mut Decoder) -> Result<Self>;
}
impl Encode for Item { ... }
impl Decode for Item { ... }
```
This is very popular pattern, most commonly known in [serde](https://serde.rs/), which is the facto standard for serialization/deserialization in Rust ecosystem. Re. performance, it's also pretty fast: Rust resolves correct function calls at compile time.

Put some duck tape to make the project compile again

---

yrs/src/block.rs
yrs/src/block_store.rs
yrs/src/doc.rs
yrs/src/id_set.rs
yrs/src/lib.rs
yrs/src/store.rs
yrs/src/transaction.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs

This PR is build on top of #3. I need a stable compiling branch and it was the one.
Work in progress: This PR introduces implemented `find_pivot` (equivalent of `findIndexSS` from JS API as I presume) and most of the `IdSet` (again as I assume it was supposed to be equivalent of `DeleteSet`).
- IdSet iteration is still missing - it requires adding some extra stuff to `Transaction` which I'm still figuring out.
- I want to introduce tests for implemented functions, but still need to figure that part out. Maybe I'll have to postpone them until a Doc API will be more complete. We'll see.

Implement find_pivot and IdSet

---

lib0/benches/lib0_benchmarks.rs
lib0/src/any.rs
lib0/src/decoding.rs
lib0/src/encoding.rs
lib0/tests/encoding_test.rs
yrs/src/block.rs
yrs/src/block_store.rs
yrs/src/doc.rs
yrs/src/event.rs
yrs/src/id_set.rs
yrs/src/store.rs
yrs/src/transaction.rs
yrs/src/updates/decoder.rs
yrs/src/updates/encoder.rs

This PR does a bunch of things related to encoding/decoding:
1. Changes naming conventions to follow Rust style in remaining methods (eg. `write_uint32`&rarr;`write_u32`, `write_uint32_big_endian` &rarr; `write_u32_be`). I already did some of that in the past, now it's complete thru ought entire code base.
- One thing Rust didn't precise was notion of var ints (as they are not Rust concept). There I used analogy: if Rust names 32-bit int as `i32` and 32-bit uint as `u32`, then I've changed `write_var_int`&rarr;`write_ivar` and `write_var_uint`&rarr;`write_uvar`.
2. Since lib0 `Encoder`/`Decoder` bear almost 1-to-1 resemblance to Rust [io::Read](https://doc.rust-lang.org/std/io/trait.Read.html) and [io::Write](https://doc.rust-lang.org/std/io/trait.Write.html) traits, I've abstracted their …

Unified encoding/decoding

---

yrs/benches/benches.rs
yrs/examples/custom_provider.rs
yrs/examples/example.rs
yrs/src/alt.rs
yrs/src/block.rs
yrs/src/block_store.rs
yrs/src/compatibility_tests.rs
yrs/src/doc.rs
yrs/src/id_set.rs
yrs/src/store.rs
yrs/src/test_utils.rs
yrs/src/transaction.rs
yrs/src/types/map.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
yrs/src/update.rs

Missing: tests - I think it would be a good idea to implement them directly on top of simulation framework (PR #26).

YMap implementation

---

.github/workflows/main.yml

Hi Kevin, 
Here is the github actions workflow to publish automatically on PyPI when creating a release.
To make it work, you'll have to set 2 secrets in your repository, by going into Settings >  Secrets > New Repository Secret.
These two keys must be named : `PYPI_USERNAME` and `PYPI_PASSWORD` and hold their respective values.
more details here if necessary : https://docs.github.com/en/actions/reference/encrypted-secrets
Keep me updated once you publish your first release on your own ! 🙂🎉

Automated publication on PyPI when releasing - using Github Actions

---

yffi/src/lib.rs
yrs/benches/benches.rs
yrs/src/block.rs
yrs/src/block_store.rs
yrs/src/compatibility_tests.rs
yrs/src/doc.rs
yrs/src/id_set.rs
yrs/src/store.rs
yrs/src/test_utils.rs
yrs/src/transaction.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs

Initial B.1 class benchmark results over incrementing sets of 1000/3000/6000 ops (compared against benchmarks from [https://github.com/dmonad/crdt-benchmarks](https://github.com/dmonad/crdt-benchmarks)):
[B1.1] Append N characters - time:   
- N=1000: **761.37 us**
- N=3000: **2.2541 ms**
- N=6000: **4.5685 ms** (Yjs v13.3: 303 ms, Automerge v0.14: 2.460 s) - Yjs is 66x slower, Automerge is 538x slower
[B1.2] Insert string of length N - time:   
- N=1000: **1.2714 us**
- N=3000: **2.7022 us**
- N=6000: **4.9906 us** (Yjs v13.3: 7 ms, Automerge v0.14: 2.981 s) - Yjs is 1,402x slower, Automerge is 597,394x slower
[B1.3] Prepend N characters - time:   
- N=1000: **755.88 us**
- N=3000: **2.3259 ms**
- N=6000: **4.6414 ms** (Yjs v13.3: 280 ms, Automerge v0.14: 83.488 s) - Yjs is 60x slower, …

Benchmarks and fixes

---

tests-ffi/include/libyrs.h
tests-ffi/main.cpp
yffi/src/lib.rs
yrs/src/block.rs
yrs/src/doc.rs
yrs/src/lib.rs
yrs/src/store.rs
yrs/src/transaction.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
yrs/src/update.rs
ywasm/src/lib.rs

1. Blocks lengths are now always counted by UTF16 standard - for compatibility with Yjs.
2. Added `Doc` options with an encoding setting, that can be used to determine what kind of encoding to use (utf8 byte length, utf16 chars or utf32 chars) in order to perform `YText` offset/length related operations. This is crucial for cross-platform support - also since blocks are always computed by utf16 standard, replicating documents could have different encoding schemes and everything still should work.

Configurable charset encoding

---

Cargo.lock
y-py/.gitignore
y-py/Cargo.toml
y-py/src/lib.rs
y-py/tests/test_helper.py
y-py/tests/test_y_array.py
y-py/tests/test_y_doc.py
y-py/tests/test_y_map.py
y-py/tests/test_y_text.py

Adds Y.rs bindings for Python:
- Current API supports `YDoc`, `YTransaction`, `YText`, `YArray`, and `YMap` with more to come.
- Major functions are documented with adapted examples from `ywasm`
- Tests are available for `YText`, `YArray`, and `YMap` in Python using `pytest`
Thanks to the maintainers working on the `ywasm` project! I based Y-Py on your JavaScript bindings and it made the process far easier to have a solid codebase from the start.

Y-Py Basic Implementation

---

yrs/src/doc.rs

Related #68 
AFAIK, this shouldn't bring any issues. `Send` is mostly about referencing structures between the threads. It won't automagically work without locks anyway, so the only thread capable of changing the document state is the one that acquired lock.

Impl Send for Doc

---

yffi/src/lib.rs

Fix suggestion for https://github.com/y-crdt/y-crdt/issues/83
I also see another fix : keep using `c_char` for change the value of negative constants for something < 128.
IMO relying on i8 is just clearer as we simply are talking about constants. From the outside, it's not really important what the actual values are as the ffi user is supposed to use the constants anyway. The functions/structs expect these constants in their interface, as per their documentation, not magic values.

[yffi] Fix negative c_char

---

yrs/src/update.rs

The current implementation of the function is incorrect, it just calls itself. I believe the original idea was to delegate the call to the `Block::same_type` function. 
Feel free to close this if the fix is not correct.

Fix stack overflow in update.rs

---

yffi/src/lib.rs
yrs/src/block.rs
yrs/src/compatibility_tests.rs
yrs/src/store.rs
yrs/src/transaction.rs
yrs/src/types/mod.rs
yrs/src/types/xml.rs
yrs/src/updates/decoder.rs
ywasm/src/lib.rs

Fixes #94
Allows to pass reusable strings in places like XML node names and formatting attribute start/end blocks.

Replaced Box<str> with Rc<str> for XML node names and content format

---

yrs/src/update.rs

Fixes https://github.com/y-crdt/ypy/issues/28 (at least the part we know about). The issue was in check if ID of an incoming update was within a local state vector bounds. 
This caused the update that had origin, which was pointing to an unknown block, being treated as a correct one, in result trying to integrate it when its left origin was still missing in local Doc.

Fixed Update::missing to return proper client when origins or parent were not found

---

yrs/src/lib.rs

While I made the `AfterTransactionEvent` struct public, I forgot to export it in lib.rs. Ypy needs access to this to address the [YDoc events issue](https://github.com/y-crdt/ypy/issues/41)

Export `AfterTransactionEvent`

---

yrs/src/doc.rs

- Added the `unobserve_transaction_cleanup` method which mirrors the `unobserve` methods on each specific YType. This will be used to unsubscribe [the same lifecycle events in Ypy](https://github.com/y-crdt/ypy/issues/41).
- Updated the associated test case.

Added unobserve method to doc

---

.github/workflows/release.yml
Cargo.lock
lib0/Cargo.toml
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

Fixes:
- Fixed content splicing when UTF-32 is in use.
- Fixed lib0 v2 encoding for string decoder (which uses UTF-16 based offsets)

Release v0.8.1

---

tests-ffi/include/libyrs.h
tests-ffi/main.cpp
tests-wasm/package-lock.json
yffi/src/lib.rs
yrs/src/compatibility_tests.rs
yrs/src/doc.rs
yrs/src/event.rs
yrs/src/store.rs
yrs/src/test_utils.rs
yrs/src/transaction.rs
ywasm/src/lib.rs

Previous implementation on `on_update` callback was basically unchanged for over a year - it didn't do full job, as it was only called when `transaction.apply_update` was called. This PR fixes that behavior and triggers the callbacks on any changes found in the transaction during a commit. 
Changes:
- `Do::on_update` is now split into `Doc::on_update_v1` and `Doc::on_update_v2` because the nature of how these callbacks are triggered, has changes. We no longer have `Update` struct at the moment of calling them, so it's better to make it aligned with Yjs behavior.

Fix: call update events callbacks on any changes in committed transactions

---

.github/workflows/release.yml
Cargo.lock
lib0/Cargo.toml
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- Fixed issues with update event not firing when transaction made changes other than apply_updates. This change required altering API: modified `Doc::on_update` &rarr; `Doc::on_update_v1`/`Doc::on_update_v2`.

release v0.9

---

yrs/src/block.rs
yrs/src/doc.rs
yrs/src/store.rs
yrs/src/transaction.rs

This PR introduces several fixes that were discovered while working on `observe_udpdate_vX` observers. It turned out that transaction changed block that was merged, generated update payload would serialize entire block instead of just new part.

Fixed encode with offset

---

yrs/Cargo.toml

Crates.io uses old repo URL: https://crates.io/crates/yrs

Use correct repo URL in Cargo.toml

---

lib0/src/any.rs

There is a BigInt type that holds an i64 but there was no `impl Into<Any>` for that.

Implement Into<Any> for i64

---

Cargo.lock
yrs/Cargo.toml

Rand's wasm-bindgen feature will enable wasm-bindgen feature on
getrandom crate which will compile wasm-bindgen package only for wasm
target: https://github.com/rust-random/getrandom/blob/v0.1.1/Cargo.toml#L35:L36
This means that on non-wasm targets wasm-bindgen is no longer included
and reduces the amount compiled crates from 37 to 15.

Remove wasm-bindgen from yrs

---

yrs/src/transaction.rs

Fixes https://github.com/y-crdt/ypy/issues/63
The issue repeat steps:
1. We delete some blocks.
2. We apply update which contains delete set. 
3. We delete blocks marked in delete set - they are partially overlapping with blocks from pt.1.
4. These blocks are added to transaction `merge_blocks` list.
5. We squash these blocks as part of another process. 
6. In result of squashing the block is incorporated into its left neighbour and deallocated. However we still have a hanging reference to it in `merge_blocks` list which now points to a garbage data.
I still need to verify scenarios, where commented out code would make a difference, but for a validity sake this is a right thing to do.

Fix: block ptr added to Transaction::merge_blocks is deallocated while pointer remains

---

lib0/src/decoding.rs

Running the lib0 decoding tests under miri reports Undefined Behavior:
```rs
Undefined Behavior: type validation failed at [0]: encountered uninitialized bytes
--> /root/build/src/decoding.rs:171:9
|
171 |         std::mem::transmute::<_, [u8; 8]>(b)
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed at [0]: encountered uninitialized bytes
```
https://github.com/y-crdt/y-crdt/blob/f9018988fa8396d44b46488b24ed775a8f17aac7/lib0/src/decoding.rs#L115-L118
This transmute attempts to transforms an uninitialized `[MaybeUninit<u8>; 8]` to `[u8; 8]` which of course is illegal.
Just zero-ing the buffer leads to the exact same assembly in -O2 and -O3, so this should have no performance impact: [godbolt](https://godbolt.org/z/qfW9f9M7s)

Fix uninitialized memory UB in lib0

---

yrs/src/block.rs
yrs/src/types/text.rs

Fixes #156 (hopefully permanently this time).

Fixed Text::remove_range for even/odd-byte length chars

---

yrs/src/transaction.rs
yrs/src/types/text.rs

Related to #156
The reason why the issue reappeared this time was due to fact, that I've assigned `OffsetKind::UTF16` correctly in text remove method but not in text find_position.

fixed invalid encoding param for block splitting in text cursor positioning

---

yrs/src/block.rs
yrs/src/id_set.rs
yrs/src/types/mod.rs
ywasm/src/lib.rs

In this function you use the unsafe keyword for some safe expressions.
We need to mark unsafe operations more precisely using unsafe keyword. Keeping unsafe blocks small can bring many benefits. For example, when mistakes happen, we can locate any errors related to memory safety within an unsafe block. This is the balance between Safe and Unsafe Rust. The separation is designed to make using Safe Rust as ergonomic as possible, but requires extra effort and care when writing Unsafe Rust.
Hope this PR can help you.
Best regards.
**References**
https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html
https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html

The scope of the unsafe block can be appropriately reduced

---

lib0/src/decoding.rs
lib0/src/encoding.rs
lib0/src/number.rs
yrs/src/compatibility_tests.rs
yrs/src/updates/decoder.rs
yrs/src/updates/encoder.rs

Fixes #188
Fixes #189
This PR solves a problem of `-0`/`0` differentiation in lib0 v2 encoding which is necessary and present in Yjs, but due to Rust nature (which doesn't recognize signed 0) was implicitly erased in Yrs, causing problems with compatibility.
Kudos to @namse for tracking down this issue. This PR also fixes it on both encoding/decoding sides.

added explicitly signed varint for lib0 v2 encoding compatibility

---

Cargo.lock
yrs/Cargo.toml
yrs/src/block_store.rs
yrs/src/doc.rs
yrs/src/store.rs
yrs/src/transaction.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs

Merge after #210
Perf benchmarks against `bart/xml-fragment` branch - in general we expected some performance degradation, since we've moved to use atomic hardware intrinsic ops to avoid risks of caching ref counters in L-caches. These ops are slower, but they are used only for establishing transactions and creating shared types.
```
[B1.1] Append N characters/6000
time:   [13.903 ms 16.477 ms 19.038 ms]
change: [-6.2946% +7.2149% +23.976%] (p = 0.37 > 0.05)
No change in performance detected.
[B1.2] Insert string of length N/1
time:   [7.6692 us 7.6861 us 7.7223 us]
change: [+24.088% +42.258% +54.557%] (p = 0.00 < 0.05)
Performance has regressed.
[B1.3] Prepend N characters/6000
time:   [4.5485 ms 4.5655 ms 4.5955 ms]
change: [-1.3148% -0.2449% +1.1504%] (p = 0.73 > 0.05)
No change in …
```

Store - use Arc & AtomicRefCells to multithreaded access

---

tests-ffi/include/libyrs.h
yffi/src/lib.rs
yrs/benches/benches.rs
yrs/src/compatibility_tests.rs
yrs/src/doc.rs
yrs/src/test_utils.rs
yrs/src/transaction.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs
yrs/src/update.rs
ywasm/src/lib.rs

This PR resolves confusion around root-level type creation:
1. All root level types that were responsible for getting or creating root-level types have changed the naming convention: `Doc::get_*` to `Doc::get_or_insert_*`. Naming convention is taken from Rust standard library (eg. [Option::get_or_insert](https://doc.rust-lang.org/std/option/enum.Option.html#method.get_or_insert_default))
2. Readonly transaction now have read-only accessor for these root-level types. These methods are using a convention of `Transaction::get_{X}(self, name: &str) -> Option<{X}>`. If the type was not defined previously a `None` case will be returned.
3. Yffi has a function to reflect pt. 2 -> `ytype_get` - since yffi function returns an ambiguous branch pointer, it doesn't need to be typed per each Y-type …

Renamed root-level accessors Doc::get_* -> Doc::get_or_insert_*

---

yrs/src/types/text.rs
yrs/src/updates/decoder.rs

Embeds are encoded to JSON but read as if there were binary encoded.
```
thread 'types::text::test::embed_with_attributes' panicked at 'Unable to read Any content'
```

Fix embeds V2 decoding

---

tests-wasm/package-lock.json
yffi/src/lib.rs
yrs/src/block.rs
yrs/src/block_iter.rs
yrs/src/doc.rs
yrs/src/moving.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs
yrs/src/undo.rs
ywasm/src/lib.rs

1. `Text::insert_embed`/`Text::insert_embed_with_attributes` now can accept shared preliminary types (eg. YMap, YArray). These types are also correctly serialized deserialized, and insert embed methods return a reference to integrated types eg. `txt.insert_embed(txn, 0, TextPrelim::new("init value"))` returns a `TextRef`.
2. Same for return values of `Map::insert`, `Array::insert`, `Array::push_back` and `Array::push_front` - all of them now return an integrated value. This simplifies situations when we wanted to insert a nested shared type, which we wanted to work with right afterwards.

Enable shared types to be passed into Text::insert_embed

---

Cargo.lock
lib0/Cargo.toml
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
yrs/src/doc.rs
ywasm/Cargo.toml
ywasm/LICENSE

- Introduction of `UndoManager`.
- Transactions can now define origins - see: `Doc::transact_mut_with`.
- `Text::insert_embed` and `Text::insert_embed_with_attributes` now accept preliminary types - including shared y-types. These methods will now return a references to an integrated types.
- `Map::insert`, `Array::insert`, `Array::push_back` and `Array::push_front` will now return a reference to an integrated type if a nested preliminary shared y-type was inserted via these methods.

release v0.15

---

yrs/src/doc.rs

Noticed few typos while reading the docs.

Fix typos in `observe/unobserve_update_v2` docstrings

---

Cargo.lock
tests-ffi/include/libyrs.h
tests-ffi/main.cpp
tests-wasm/index.js
tests-wasm/relative-position.tests.js
yffi/cbindgen.toml
yffi/src/lib.rs
yrs/src/block_iter.rs
yrs/src/lib.rs
yrs/src/moving.rs
yrs/src/store.rs
yrs/src/types/array.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs
yrs/src/undo.rs
yrs/src/update.rs
ywasm/src/lib.rs

This PR changes a `RelativePosition` in order to make it into an exposed structure. It basically allows us to have a "sticky" point of reference for the index in a shared y-type collection that will always place into the same position even when concurrent updates are about to happen. This is very useful i.e. in rich text editors that want to keep cursor position while other peers change the document.
Relative position is serializable and can be turned back and forth between an actual index (as interpreted by humans).
Related to: #241 and #184

Expose RelativePosition API

---

tests-ffi/include/libyrs.h
tests-ffi/main.cpp
tests-wasm/index.js
tests-wasm/sticky-index.tests.js
yffi/cbindgen.toml
yffi/src/lib.rs
yrs/src/block_iter.rs
yrs/src/lib.rs
yrs/src/moving.rs
yrs/src/types/array.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs
yrs/src/update.rs
ywasm/src/lib.rs

Renamed `RelativePosition` to `StickyIndex`.

Rename RelativePosition to StickyIndex

---

tests-ffi/include/libyrs.h
tests-ffi/main.cpp
yffi/src/lib.rs

Related to #246
In general from cross-platform C point of view standard definitions like char, int etc. are not guaranteed to be the same across different platforms. Hence the definitions like `uint8_t`, `uint32_t` etc.
This PR changes libyrs.h header to make use to these universal type definitions.

yffi: changed int types to use type definitions from stdint.h

---

Cargo.lock
lib0/Cargo.toml
yffi/Cargo.toml
yrs/Cargo.toml
yrs/src/lib.rs
ywasm/Cargo.toml

- Fixed #253 : infinite loop in `Doc::to_json` when sub-documents are present
- Fixed #254 : lib0 v2 encoding of JSON-like structures (visible in formatting attributes decoding)

release v0.16.1

---

yrs/src/doc.rs
yrs/src/update.rs

fix #268 
changes:
1. Modify the sorting of lazy_struct_decoders to ordering.reverse() to meet the requirement of descending order sorting by clientId, and resolve the issue of lost updates (unittest: modified `update_merge`).
2. Refactor the `if let .. {} else { continue/break }` structure to `let .. = match { _ => break/continue }` to reduce indentation and make the code more readable.
3. Replace `curr_write.take()` and `curr.take()` with references. The former moves ownership, causing subsequent calculations to lose access to the corresponding state.
4. To reference the block of the current iteration, I removed the `impl Iterator for Memo` and replaced it with the `next_item()` method, the former will not be available in the next iteration after the `next` method is called in the …

Fix some inconsistencies in the Update::merge_updates method with Y.js.

---

lib0/src/any.rs

While I was digging around in the existing language bindings, I back-tracked to Any (since it features prominently) - and thought it might be helpful to have a small bit of detail in the docs about what it represents.

Add a documentation note defining lib0::Any

---

yrs/src/block_iter.rs
yrs/src/types/array.rs

Fixed - BlockIter ends prematurely if last array element has been moved

---

yrs/src/types/array.rs

While working on an upgrade of `ypy` to `yrs` v0.16.2 I noticed one of the `ypy` tests failing on a `debug_assert!` in `yrs`.
I recreated the [Python test case](https://github.com/y-crdt/ypy/blob/0df9bfe012b79d6e4f4d0c85e95a4bb59fd444c3/tests/test_y_array.py#L254) in Rust in `yrs` and it fails on this line:
https://github.com/y-crdt/y-crdt/blob/31b309868006d14c47c5deac6875979245de6409/yrs/src/moving.rs#L106
It fails while doing a `to_json` on an array [after the "Move 3-5 to 5" part](https://github.com/stefanw/y-crdt/blob/test-move_range_to/yrs/src/types/array.rs#L1479-L1482) of the test.
If you remove previous parts the tests often pass though! So it looks like this particular sequence of transactions causes the failure. Sorry that it's not a minimal test case but I really wouldn't know …

Slice does not always fit block range (adds move_range_to test from ypy)

---

yrs/src/lib.rs

Currently, the `AfterTransactionSubscription` can not be used from outside crate. So this PR expose the `AfterTransactionSubscription`

Expose AfterTransactionSubscription type

---

yrs/src/types/mod.rs

Improve the documentation of the `observer_deep` function.

docs: update observer_deep documentation

---

tests-wasm/editing-traces.tests.js
tests-wasm/index.js
tests-wasm/package-lock.json
tests-wasm/package.json
ywasm/src/lib.rs

This PR fixes an issue when non UTF-16 offset encoding was used if `new Y.Doc()` was used in y-wasm. We also extend Seph Gentle's editing-trace tests integrated in yrs last time onto y-wasm as well.

fixed issue with non utf-16 encoding on default y-wasm doc settings

---

Cargo.lock
tests-wasm/package-lock.json
ywasm/Cargo.toml

- fixed `new YDoc()`: utf-16 encoding was not set when no option parameter has been sent to constructor

y-wasm release v0.16.6

---

yrs/src/id_set.rs
yrs/src/update.rs

Related to #295
This PR is a brute force fix for issue with V2 encoding, when `DeleteSet` is being serialized before being squashed.

fixed DeleteSet encoding over unsquashed DeleteSet

---

yffi/src/lib.rs
yrs/benches/benches.rs
yrs/src/block.rs
yrs/src/doc.rs
yrs/src/moving.rs
yrs/src/store.rs
yrs/src/tests/compatibility_tests.rs
yrs/src/transaction.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs
yrs/src/update.rs
yrs/src/updates/decoder.rs
ywasm/src/lib.rs

This PR introduces 2 changes:
1. Replaced basically all cases when `Rc<str>` was used with `Arc<str>`. This adds cross-thread safety and enables us to share some of the strings between threads (Rc cannot be passed between threads).
2. Replaces internal `u8` flag representing which shared type given Branch represents with complex enum: `TypeRef`. It's representation is made so that if maps to the same flag for serialization/deserialization, however it can have custom field eg.:
- `Branch::name` field was moved into `TypeRef::XmlElement` as that field was used only by XML elements.
- For the [WeakLinks](https://github.com/yjs/yjs/pull/539) we'll need some extra field linking.
- For `ArrayRef` and `TextRef` we'll probably need these fields to store cursor search markers.

Changed type refs enum representation

---

lib0/src/any.rs
lib0/src/json_parser.rs
lib0/src/macros.rs
lib0/src/number.rs
lib0/tests/encoding_test.rs
lib0/tests/json_test.rs
yffi/src/lib.rs
yrs/src/block.rs
yrs/src/doc.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
ywasm/src/lib.rs

Changes:
- (Following discussion from #315) Make all integer numbers < 2^53-1 convert to `Any::Number(f64)` by default. Above that threshold - use `Any::BigInt(i64)`.
- Replace `Into<Any>` trait with `From<T> for Any` as it will auto-generate `Into<Any>` equivalent anyway.
- `Any`: replace `Box` heap allocation with `Arc` (thread-safe reference counter). Why? Because when reading `ItemContent`, we did deep copies of underlying objects (it means ie. full copy of strings and binaries). Since these were heap allocated anyway, I've switched them to use refcounted variant, so now we only increment refs, which is much faster. It's also safe as `Any` are never internally modified by yrs - always replaced in full.

lib0::Any: using Arc instead of Box

---

lib0/benches/lib0_benchmarks.rs
lib0/src/any.rs
yrs/src/doc.rs
yrs/src/tests/compatibility_tests.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs
yrs/src/undo.rs

Implemented `Any::cast` and `Value::cast` methods that make it easier to specify generic type that we want to cast them to - this methods works automatically for any generic type implementing `TryFrom<Any>` and `TryFrom<Value>`. This way we also removed `Value::to_ymap`/`Value::to_ytext`/`Value::to_yarray` etc. as they can be replaced by cast method ie. `value.cast::<MapRef>`/`value::cast<TextRef>`/`value::cast<ArrayRef>` etc.

Added Any::cast, Value::cast and standarized casting rules

---

tests-ffi/include/libyrs.h
tests-wasm/y-undo.tests.js
yffi/cbindgen.toml
yffi/src/lib.rs
yrs/src/lib.rs
yrs/src/undo.rs
ywasm/src/lib.rs

Related #342
Atm. stack items have no means to attach metadata - users have to do it by themselves. This PR makes it possible. It also extends ywasm and yffi undo manager events to propagate meta field.

Added metadata info to UndoManager stack items

---

yrs/src/block.rs
yrs/src/id_set.rs
yrs/src/undo.rs

Fixes #345 
Since these issues were already fixed in Yjs but not ported to Yrs, the fixes included:
- When DeleteSet iterator was running over merged blocks, they were split at the end in an invalid order.
- Yjs redoItem over YMap entry follows redone item chain on every step when we redo items in chain from left to right. Before this PR Yrs did it only for the last item in left&rarr;right chain.
- Yjs redo checks if item was observed by undo manager marking it for deletion.

UndoManager: fixes to issue 345

---

tests-ffi/include/libyrs.h
yffi/src/lib.rs
yrs/src/block.rs
yrs/src/doc.rs
yrs/src/types/text.rs

Since `OffsetKind::Utf32` is not used anywhere, we're removing support of UTF-32 oriented offsets.

Removed OffsetKind::Utf32

---

tests-ffi/include/libyrs.h
tests-wasm/y-doc.tests.js
yffi/src/lib.rs
yrs/src/block.rs
yrs/src/block_iter.rs
yrs/src/doc.rs
yrs/src/store.rs
yrs/src/transaction.rs
ywasm/src/lib.rs

Related to #347
This PR introduces set of functions to check if nested shared collection has been destroyed (therefore checked reference is no longer valid and using it will panic):
- *yrs*: `transaction.is_alive(&map_ref)` etc.
- *ywasm*: `map_ref.alive(transaction)`
- *yffi*: `ytransaction_alive(transaction, map_ref)`
This implementation is using a set in document store that keeps information about valid branch pointers around. It's filled and emptied when branch type is integrated or deleted from the document store.
In related discussion we were talking about replacing BranchPtr with synthetic pointer that's only valid in scope of the transaction however that's not fully possible in current design, since it would require to *all* operations related to shared collection to have a …

added methods to check if shared collection references has been deleted

---

.github/workflows/main.yml
yffi/Cargo.toml
yrs/Cargo.toml
yrs/src/block.rs
yrs/src/lib.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs
ywasm/Cargo.toml

This PR introduces a new feature flag "weak" turns on `WeakRef` and related features (ie. `Map::link` or `Quotable` trait).
It's turned off by default on yrs, however since yffi and ywasm cannot reference yrs conditionally, it's turned on for both of them.

Feature flag: weak

---

Cargo.lock
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- #261 WeakRef feature (requires `features=["weak"]`)
- #321 Replace boxing with atomic ref counters in Any
- #325 merge lib0 into yrs
- #322 simpler casting from `Value` to other types
- #342 UndoManager stack items can now hold metadata objects
- #348 fixed several issues in UndoManager causing invalid undo/redo steps
- #353 ywasm: exposed Transaction as an argument in observer callbacks
- #350 removed support for UTF-32 offset counting
- #351 added a way to verify in nested shared collection point to an alive/dead object
- #324 removed custom JSON serialisation and use serde instead

release v0.17

---

yffi/src/lib.rs
yrs/src/types/mod.rs
ywasm/src/lib.rs

Related to #307 
This PR introduces a new type of `Value` - and `Value::UndefinedRef(BranchPtr)`. While this is one of "shouldn't happen" scenarios, it can happen when ie. when used to iterate over root types after between application in different versions.
As part of a process to remove panics from code it seems sensible to introduce this change.

introduced Value::UndefinedRef

---

yffi/src/lib.rs
yrs/src/block.rs
yrs/src/block_store.rs
yrs/src/encoding/read.rs
yrs/src/update.rs

Replace the use of `with_capacity` with `try_reserve` in collections specifically when decoding the `Update` to better handle potential memory allocation errors. For now, this change should be applied only in the context of `Update` decoding, without altering other instances of `with_capacity` usage. 
If needed, please let me know, and I can handle the remaining tasks

chore: replace from with_capacity with try_reserve

---

Cargo.lock
tests-ffi/include/libyrs.h
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- Fixed #371
- `Update::decode` introduced `Error:NotEnoughMemory`. Useful in cases when malformed update payload may cause panic during memory allocation. #369 
- Reworked garbage collected blocks to not occupy unnecessary memory. #365

release v0.17.3

---

Cargo.lock
tests-ffi/include/libyrs.h
tests-ffi/main.cpp
tests-wasm/package-lock.json
tests-wasm/y-undo.tests.js
yffi/cbindgen.toml
yffi/src/lib.rs
yrs/Cargo.toml
yrs/src/block.rs
yrs/src/block_store.rs
yrs/src/doc.rs
yrs/src/gc.rs
yrs/src/id_set.rs
yrs/src/lib.rs
yrs/src/observer.rs
yrs/src/store.rs
yrs/src/test_utils.rs
yrs/src/transaction.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
yrs/src/types/weak.rs
yrs/src/types/xml.rs
yrs/src/undo.rs
yrs/src/update.rs
ywasm/src/lib.rs

This PR introduces a new way to work with events and observers. There's a lot of simplifications inside but most notable ones are:
1. More strict callback function type definitions - previously it was `Observer<Arc<dyn Fn(&TransactionMut, &E) -> ()>>`. Now it's just `Observer<E>` or `ObserverMut<E>` depending if we want to pass readonly or mutable references.
2. All different kinds of subscriptions ie. `UpdateSubscription = Subscription<Arc<dyn Fn(&TransactionMut, &UpdateEvent>>` are now conflated into one: `yrs::Subscription`.
3. No more `SubscriptionId` - just use `Subscription` and drop it if it's no longer needed.
4. No more dozens of `unsubscribe` methods. Either `drop` (yrs), `free` (ywasm) or `yunobserve` (yffi) is all you need.
This PR includes new mechanics like delayed cleanup …

New observers

---

yrs/src/lib.rs
yrs/src/observer.rs
yrs/src/sync/awareness.rs
yrs/src/sync/mod.rs
yrs/src/sync/protocol.rs

This PR moves [y-sync]() protocol crate features directly into yrs. The reason is that these features are very closely related to the core crate, while they don't introduce any new dependencies.

moved ysync protocol into yrs

---

Cargo.lock
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- New Observer API (#385): all subscription types now are described as a single `yrs::Subscription` type. `observe` methods no longer require `mut ref` to shared collection or document.
- `Hook` and `BranchID` logical pointers (#393): collection refs such as `ArrayRef`, `TextRef`, `MapRef` now expose `root` and `hook` methods, that can be used to get a logical reference to a given type. This reference can later on be used to try to obtain an actual ref (it could also possibly return `None` if reference was already garbage collected).
- Removed `Doc::get_or_insert_xml_element` and `Doc::get_or_insert_xml_text` - these types are not meant to be used as root level types and doing so may cause data loss due to limitations on how root-level types are represented in lib0 encoding.
- Replaced …

release v0.18

---

yrs/src/block.rs
yrs/src/update.rs

Fixes #391
The reason for original panic was that deleted block sent in a 2nd update didn't have a parent specified - such block should be replaced by GC placeholder instead. However it didn't, and the corresponding parent haven't been defined, which caused errors during document state encoding.

fixed: integrating update block without parent causes panic on subsequent encode

---

Cargo.lock
tests-ffi/include/libyrs.h
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- AwarenessUpdate: exposed member + added Serialize/Deserialize trait impls: #397 
- Fix undo manager issue caused by redo steps skipping over merged blocks: #401
- Fix integration issue cause by not replacing deleted blocks without parent specified with GC: #402

release v0.18.1

---

tests-ffi/include/libyrs.h
yffi/src/lib.rs
yrs/src/store.rs
ywasm/src/transaction.rs

This PR exposes pending update and pending delete set for the users to see, so that they can react accordingly.

expose pending update and pending delete set

---

yrs/src/doc.rs
yrs/src/sync/awareness.rs

This PR includes `AwarenessUpdate` changes as part of the `awareness::Event`. There's no reason not to do that, since basically the main rationale behind having observer on awareness changes is to produce that payload.

add AwarenessUpdate as part of the awareness::Event

---

Cargo.lock
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- added `Awareness::apply_update_summary` method - used in order to expand capabilities of awareness update generation outside of the limits of Rust closures: #424
- updated dependencies: arc-swap, smallvec, fastrand

release v0.18.5

---

yrs/src/block.rs
yrs/src/types/text.rs

There's a missing case where `Text::insert` checks for empty strings and produces a no-op. However the same should apply to `Text::insert_with_attributes` (yes, in such case attributes are not inserted which is a compatible behaviour to Yjs). Otherwise we would produce an empty block, which in turn would cause encoding (and potentially many other operations) to panic.

fix: Text::insert_with_attributes should not generate empty blocks

---

Cargo.lock
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- enable decoding 0-length blocks from pre-v0.18 encoded yrs documents: #428

release v0.18.7

---

README.md
yrs/src/sync/awareness.rs

Since v0.18 `Awareness` is no longer provided as part of the `Awareness::on_update` callback. Quite often however we want to have an access to its internal functions: ability to serialise on_update changes, full awareness state, introspection of specific clients etc.
This PR adds more of these capabilities into awareness `Event` object.

Awareness on_update: provide awareness state in the event

---

Cargo.lock
tests-wasm/awareness.tests.js
tests-wasm/index.js
yrs/Cargo.toml
yrs/benches/benches.rs
yrs/src/doc.rs
yrs/src/sync/awareness.rs
yrs/src/sync/mod.rs
yrs/src/sync/time.rs
ywasm/src/awareness.rs
ywasm/src/lib.rs

This PR does 2 things:
1. Removes dependency on `std::time` from yrs. Instead it introduces a generic notion of `Clock` and `Timestamp`. This can be used in non-wasm targets as well as for things like mocking time for tests. Related to #442
2. Introduces `Awareness` class and methods in **ywasm** crate. The API is modelled after [y-protocols](https://github.com/yjs/y-protocols/blob/master/awareness.js) Awareness class. It also tests compatibility of yrs::Awareness with wasm-32 target.
TODOs: tests for Awareness.

ywasm: awareness

---

tests-ffi/CMakeLists.txt
tests-ffi/main.cpp

This PR fixes the FFI unit tests on Windows. 
Thanks to @MarkJGx (https://github.com/MarkJGx) for helping do this.
CMake:
- Ensure C++20
- Ensure UTF-8 Encoding
C++:
- Ensure YRS destroy functions are called where needed
- explicitly allocate char*s

Fixing FFI Unit Tests for Windows

---

yrs/Cargo.toml
yrs/src/branch.rs
yrs/src/doc.rs
yrs/src/lib.rs
yrs/src/observer.rs
yrs/src/store.rs
yrs/src/sync/awareness.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
yrs/src/undo.rs

This PR modifies previous conditional observer API compilation to make use of dedicated feature flag `sync` instead of hardcoding it to `wasm` family target. This way users can pick if their observers are supposed to work in multithreaded environment (at least withing Rust guarantees) using feature flags.

feature: sync

---

yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs

This PR introduces 2 new features:
1. `DefaultPrelim` trait implemented by `MapRef`/`ArrayRef`/`TextRef`/`XmlFragmentRef`/`XmlTextRef`, which allows for automatic conversion between these types and their prelim equivalents.
1. `MapRef::get_or_init` method which enables returning an element of a given type or initialize it to a given type if it didn't met the expectation. It's using `DefaultPrelim` type to perform initialization.

MapRef::get_or_init and DefaultPrelim trait

---

yrs/src/encoding/serde/mod.rs
yrs/src/encoding/serde/ser.rs

This PR introduces tests for conversion between common `Any` and `serde_json::Value`s. The crux here is that `Any` by default supports only floating point numbers (because of Yjs compatibility), so that even integers are converted to them. However for many cases, we actually want to use integers. For that in serde serialiser we first check if number can be converted to integer (it has no fractional part).

make yrs::Any conversion to serde_json::Value more seamless

---

tests-ffi/include/libyrs.h
yffi/src/lib.rs
yrs/src/branch.rs
yrs/src/encoding/read.rs
yrs/src/encoding/serde/de.rs
yrs/src/out.rs
yrs/src/types/map.rs
yrs/src/types/text.rs
yrs/src/types/weak.rs
yrs/src/types/xml.rs

Changes in this PR:
1. `MapRef::get_as`: a convenience method that attempts to convert MapRef entry into strongly typed Rust value.
2. `MapRef::try_update`: a convenience method that attempts to update a MapRef entry, but only if the inserted value differs from existing one. This may be useful in order to prevent overriding entry with the same value, which would cause tombstone accumulation.
3. Replaced shared type conversions from `Into` to `AsRef`.
4. Deserializing `Any` value now returns a `yrs::encoding::read::Error`.

MapRef methods: get_as and try_update

---

Cargo.lock
tests-ffi/include/libyrs.h
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- New methods: 
- `Array::get_as` for casting `Out` value getter to strong Rust types.
- `Map::get_as` for casting `Out` value getter to strong Rust types.
- `Map::try_update` for conditional insertion of values (to prevent unnecessary tombstone generation).
- `UndoManager::undo_stack` and `UndoManager::redo_stack` accessor methods to inspect corresponding undo manager data.
- Removed `Clone` trait from `UndoManager` as it's unsafe for practical use.

release-v0.19.1

---

yrs/src/observer.rs

SubscriptionId was removed some time ago, and, as far as I can tell, there isn't functionality to replace it. I stumbled on this until I realized I needed to turn on the "sync" feature to pass a subscription between threads.

Remove stale comment about Subscriptionid

---

yrs/src/block.rs
yrs/src/block_iter.rs
yrs/src/branch.rs
yrs/src/out.rs
yrs/src/store.rs
yrs/src/tests/compatibility_tests.rs
yrs/src/transaction.rs
yrs/src/types/array.rs
yrs/src/types/map.rs
yrs/src/types/mod.rs
yrs/src/types/text.rs
yrs/src/types/xml.rs
yrs/src/update.rs

Original issue was that while we make checks if user is not trying to insert empty text into `TextRef` this didn't work for `Text::apply_delta`. 
It was a symptom of more general issue - we shouldn't be able to create Item blocks with empty contents in the first place. This PR solves while gracefully ignoring user attempts to do an invalid operation.

make sure that empty items are never created

---

yrs/src/types/xml.rs

Currently, there is no way to build XmlIn other than `as_prelim`.
As background, I am currently implementing elixir binding and am having trouble[ encode/decode prelim to elixir types.](https://github.com/satoren/y_ex/pull/40/files#diff-0543d4713142d5424d993a2a571f2a0b0e01f1751bf81feb7fa321538e617526R89)

alow direct construction of XmlDeltaPrelim

---

Cargo.lock
yrs/Cargo.toml
yrs/src/lib.rs
yrs/src/sync/awareness.rs
yrs/src/sync/protocol.rs
ywasm/src/awareness.rs

This PR changes `Awareness` implementation to make it able to work without relying on `&mut` references. It's solved internally by using [dashmap](https://crates.io/crates/dashmap) crate. Together with #481 this enables us to provide entire y-sync `Protocol` support without using external locks.

make Awareness thread-safe by default

---

Cargo.lock
yrs/Cargo.toml
yrs/src/sync/awareness.rs
yrs/src/sync/protocol.rs

This PR introduces few changes:
1. y-sync `Protocol` now summarizes all message handlers under a single `handle` method. We previously avoided that since `Doc`/`Awareness` might have been hidden behind locks, that were not defined at protocol level but rather by users.
2. Introduces y-sync `AsyncProtocol` which is `Protocol` equivalent, however it acquires transactions using `AsyncTransact` API introduced before in #481 .

implement async y-sync protocol

---

tests-ffi/main.cpp
yffi/src/lib.rs

This PR comes with yffi tests confirming that inputs/outputs can be read write between any primitive types. Original discovered issue was that JSON map could not be properly read through C FFI.

yffi: tests for input and output

---

Cargo.lock
tests-ffi/include/libyrs.h
tests-ffi/main.cpp
yffi/Cargo.toml
yffi/src/lib.rs

This PR extends yffi API to enable working with JSON input and output data:
1. `yinput_json(*char)` can take any well-formed, utf-8 encoded, null-terminated JSON string. This kind of input will be internally serialized as `yrs::Any` type entry.
2. `ymap_get_json` and `yarray_get_json` will return a JSON string representation of their corresponding entries. Complex types like YMap, YArray, YText etc. will have their contents also serialized into JSON representation and returned as such.
3. `ybranch_json(*Branch, *Transaction)` will return a JSON string representation of any branch type.

yffi: add operators to interact with JSON strings

---

Cargo.lock
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- #481: introduced `yrs::AsyncTransact` trait which works in similar way to `yrs::Transact` except transaction factory methods now return futures that can be awaited on.
- #482: `Awareness` operations now can be executed **without** `&mut Awareness` reference and are thread-safe.
- #483: y-sync `AsyncProtocol`  introduced works just like `Protocol` except it uses new `AsyncTransact` API to handle transactions required for y-sync protocol message handling in asynchronous way.
- #480: `XmlDeltaPrelim` fields are now exposed.
- `yffi`:
- #484: fixed issue when reading JSON map outputs caused segfaults.
- #485: introduced new API functions that allow to use JSON string as input types (`yinput_json`), and reading any shared ref contents back as JSON (`ybranch_json`). Additionally …

release v0.20.0

---

.github/workflows/release.yml
Cargo.lock
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml
ywasm/src/awareness.rs

- Biggest breaking change: `TransactionMut::apply_update` now returns a result, which can be errors for cases that previously caused panics.
- `UndoManager`
- instead of `undo`/`redo`, now we have 3 variants of each `try_undo`/`undo_blocking`/`undo`(async) to reflect new capabilities of asynchronous transactions.
- yffi: `yundo_manager_can_undo` and `yundo_manager_can_redo` are now replaced by `yundo_manager_undo_stack_len` and `yundo_manager_redo_stack_len` - these methods can be used pretty much the same way but they are more capable and carrt more information.

release v0.21

---

tests-ffi/include/libyrs.h
yffi/src/lib.rs
yrs/src/block.rs
yrs/src/block_store.rs
yrs/src/doc.rs
yrs/src/gc.rs
yrs/src/transaction.rs
ywasm/src/transaction.rs

This option enables `TransactionMut::force_gc` method, that can be used to ie. in scenarios where we want to keep GC for some documents, but eventually we want to compact the document's state without having to go through encode/decode/apply cycle on the new document state.

Enable force GC on all document items, regardles of skip_gc option.

---

yrs/src/update.rs

This PR introduces `Update::state_vector_lower` which presents the state vector that's a lower bound of blocks included in update (`Update::state_vector` already exists and contains upper bound). This may be useful to detect if there are missing blocks between update and state vector of document.

Introduce Update methods: state_vector_lower and delete_set

---

tests-ffi/include/libyrs.h
tests-wasm/package-lock.json
tests-wasm/sticky-index.tests.js
yffi/src/lib.rs
yrs/src/moving.rs
ywasm/src/lib.rs

This PR changes the way how `StickyIndex` is serialised to bring it closer in compatibility with Yjs. It also renames the ywasm method names to make it compatible with Yjs and exposes its JSON serialisation/deserialization methods into yffi.

Make StickyIndex JSON compatible with Yjs

---

yrs/src/block.rs
yrs/src/slice.rs

The library should panic when it fails to write the parent info for an item with a branch parent. This was done in block.rs, but was missing in slice. Add a message to `unreachable` in both places to make it easier to identify if it occurs.
I ran into this when incorrectly writing to a YMap that had just been removed from the document, resulting in a malformed update message being sent to the client.
Let me know if you prefer a different message/style, happy to make any changes.

Add unreachable check to slice encode method when item has invalid parent branch

---

yrs/src/update.rs

Added `Update::EMPTY_V1` and `Update::EMPTY_V2` constants for situations where no-op update payload could be helpful.

Added empty update constants

---

.github/workflows/release.yml
Cargo.lock
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- JSON Path support for Any and Doc
- Update:EMPTY_V1 and Update::EMPTY_V2 byte arrays for empty content
- Update::state_vector now doesn't include disjoined update blocks

release v0.23.0

---

yrs/src/branch.rs
yrs/src/types/mod.rs

Since the value is already removed, debug formatting would panic calling the Branch::id method on the reference. The best we can do is print the type, it's better than nothing.
```
internal error: entered unreachable code
stack backtrace:
0: rust_begin_unwind
at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:695:5
1: core::panicking::panic_fmt
at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:75:14
2: core::panicking::panic
at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:145:5
3: yrs::branch::Branch::id
at /.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yrs-0.23.0/src/branch.rs:273:13
4: <yrs::branch::BranchPtr as core::fmt::Debug>::fmt
at …
```

Modify EntryChange::Removed Debug formatting to avoid panics

---

tests-ffi/include/libyrs.h
yffi/src/lib.rs

Currently it's possible to get or iterate the content of the WeakRef, but not to get the current indexes into a YText back.
[This is an implementation that doesn't change the core yrs crate, only yffi; not sure if it's the best way to do it, or if i interpret the "no start_id()" case correctly...]

yffi: add yweak_read to convert WeakRef back to indexes

---

Cargo.lock
yrs/Cargo.toml

Bump this error to v2. None of the major version [release notes](https://github.com/dtolnay/thiserror/releases/tag/2.0.0) apply [here](https://github.com/search?q=repo%3Ay-crdt%2Fy-crdt+%22%23%5Berror%28%22&type=code).

Bump this error to v2

---

tests-wasm/y-doc.tests.js
yrs/src/block_store.rs
yrs/src/doc.rs
yrs/src/moving.rs
yrs/src/transaction.rs
yrs/src/types/weak.rs
yrs/src/update.rs

This PR removes a relation to `ItemPtr` from within WeakRef `LinkSource`. This should fix #536 . We used item pointers cache for faster access, but in retrospect it doesn't help a lot while introducing risk of stale memory pointers.

Weak links: remove reference to an item

---

yrs/src/store.rs
yrs/src/transaction.rs
yrs/src/update.rs

This PR adds few methods to transaction API:
- `ReadTxn::has_missing_updates` to check if we know about some missing data.
- `WriteTxn::prune_pending` which removes pending updates from the current document and returns them.

add methods to manage pending updates

---

tests-ffi/include/libyrs.h
tests-ffi/main.cpp
tests-wasm/package-lock.json
tests-wasm/y-weak-link.tests.js
yffi/src/lib.rs
yrs/Cargo.toml
yrs/src/moving.rs
yrs/src/types/mod.rs
yrs/src/types/weak.rs
ywasm/src/array.rs
ywasm/src/js.rs
ywasm/src/text.rs
ywasm/src/xml_text.rs

This PR enables unbounded quotations for weak link feature. Example:
```rust
let doc = Doc::new(1);
let mut txn = doc.transact_mut();
// text that we want to quote
let current_paragraph = txn.get_or_insert_text("id");
let quotes = txn.get_or_insert_array("quotes");
current_paragraph.insert(&mut txn, 0, "abc");
// quote everything from index 1 until the end of paragraph
let quote_prelim = current_paragraph.quote(&txn, 1..).unwrap();
let quote = quotes.insert(&mut txn, 0, quote_prelim);
quote.get_string(&txn); // "bc"
// expand the quoted paragraph
current_paragraph.push(&mut txn, "def");
quote.get_string(&txn); // "bcdef"
```

Unbounded quote

---

tests-wasm/y-doc.tests.js
ywasm/src/lib.rs

Adds WASM bindings for `mergeUpdatesV1` and `mergeUpdatesV2`, consistent with yjs.

Add mergeUpdatesV1 and mergeUpdatesV2 functions to WASM bindings

---

tests-wasm/y-xml.tests.js
yrs/src/types/xml.rs
ywasm/src/lib.rs
ywasm/src/xml.rs
ywasm/src/xml_elem.rs
ywasm/src/xml_text.rs

See #568 for context and discussion on JSON attribute support in XML methods.
yrs
- Added support for attributes with Any type via new get_attribute_any and attributes_any methods
- Preserved existing attribute* methods for backward compatibility
- Enhanced internal logic to support Any-typed attributes across XML elements
ywasm
- Extended xml.attrs* to handle Any-typed attributes
- Added test coverage for the new functionality

Add support for full JSON values in XML attribute methods

---

tests-ffi/include/libyrs.h
tests-ffi/main.cpp
yffi/src/lib.rs
yrs/src/json_path/iter_txn.rs
yrs/src/tests/compatibility_tests.rs
yrs/src/types/xml.rs
ywasm/src/xml_elem.rs
ywasm/src/xml_text.rs

This PR is follow up to #569 . Since the complexity added is almost none, we can as well not limit ourselves to insert only primitive types (including non-string ones) as attributes to XmlElementRef/XmlTextRef, but we could use any type accepted into shared maps (i.e. attribute value as TextRef?).
Since this is going to add breaking changes to next release anyway, I'm also conflating `get_attribute`/`get_attribute_any` into single method: you can always obtain string the old way by calling `xml.get_attribute(txn, key).unwrap().to_string(txn)`.

allow XML attributes to work with any Prelim type

---

Cargo.lock
tests-wasm/package-lock.json
yffi/Cargo.toml
yrs/Cargo.toml
ywasm/Cargo.toml

- XML attribute methods now accepts any Prelim type: #571, #569
- enable manual gabage collection of blocks with parametrised set of blocks to delete: #570 
- add mergeUpdates methods to ywasm: #566

release v0.24
